version: '2'

services:
  dyndoc-ruby:
    build:
      context: DockerFiles
      dockerfile: Dockerfile-dyndoc
    image: rcqls/dyndoc-ruby-DyndocRubyUbuntu

  website:
    build:
      context: DockerFiles
      dockerfile: Dockerfile-website
    image: rcqls/website-DyndocRubyUbuntu
    restart: always
    volumes:
      - RodaSrvPublic:/home/ubuntu/RodaSrv/public
      - RodaSrvTools:/home/ubuntu/RodaSrv/.tools
      - RodaSrvDyndocLibrary:/home/ubuntu/dyndoc-library
      - RodaSrvDyndocWorld:/home/ubuntu/.dyndoc-world
      - RodaToolsName:/home/ubuntu/tools
    ports:
      - RodaSrvPort:9294
    tty: true
    networks:
      - NetworkName
    external_links:
      - MongoName_mongo_1:mongo
      - MongoName_mongo-express_1:mongoexpress

networks:
  NetworkName:
    external: true