FROM rcqls/dyndoc-ruby-DyndocRubyUbuntu
MAINTAINER "Cqls Team"

USER ubuntu

RUN mkdir -p /home/ubuntu/RodaSrv/public/edit
RUN mkdir -p /home/ubuntu/RodaSrv/public/users
RUN mkdir -p /home/ubuntu/dyndoc-library
RUN mkdir -p /home/ubuntu/.dyndoc-world
RUN mkdir -p /home/ubuntu/tools/bin
RUN mkdir -p /home/ubuntu/tools/dyndoc

RUN ln -sf /home/ubuntu/tools/dyndoc dyndoc

ENV PATH=$PATH:/home/ubuntu/tools/bin


ENTRYPOINT /usr/local/bin/dyn-ctl start && /bin/bash