version: '2'

services:
  mongo:
    image: mongo
    restart: always
    environment:
        # provide your credentials here
        - MONGO_INITDB_ROOT_USERNAME=MongoUser
        - MONGO_INITDB_ROOT_PASSWORD=MongoPwd
    ports:
      - "MongoPort:27017"
    volumes:
      - MongoDir/data/db:/data/db
      - MongoDir/data/configdb:/data/configdb
    networks:
      - NetworkName
  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "MongoExpressPort:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=MongoUser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=MongoPwd
    networks:
      - NetworkName

networks:
    NetworkName:
      external: true